version: "3"

services:
    jenkins:
        container_name: jenkins
        image: jenk-ans
        build:
            context: ansible
        ports:
            - "8080:8080"
        volumes:
            - $PWD/jenkins_home:/var/jenkins_home
        networks:
            - net
    centos:
        container_name: centos
        image: centos
        build:
            context: centos
        networks:
            - net
networks:
    net:

